version: "{build}"
shallow_clone: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%CACHED_FOLDER%'

environment:
  global:
    VENV_BUILD_DIR: "%HOME%\\venv_build"
    CACHED_FOLDER: "%LOCALAPPDATA%\\cashed"
    HOME: "%HOMEDRIVE%\\%HOMEPATH%"

  matrix:
    #- PYTHON_DIR: "C:\\Python27-x64"
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    #  APPVEYORRUN: "unit"
    #- PYTHON_DIR: "C:\\Python35-x64"
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  APPVEYORRUN: "unit"
    #- PYTHON_DIR: "C:\\Python36-x64"
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #  APPVEYORRUN: "unit"
    - PYTHON_DIR: "C:\\Python37-x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      APPVEYORRUN: "unit"

install:
  - ps: |
      & "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor-before-install.ps1"
      & "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor-install-deps.ps1"

build_script:
  - ps: |
      & "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor-build.ps1"

test_script:
  - ps: |
      & "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor-test.ps1"

on_failure:
  - ps: |
      & "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor-rdp.ps1"

on_finish:
  - ps: |
      & "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor-finish.ps1"

#artifacts:
#  - path: dist\*
