channels:
  - conda-forge
dependencies:
  - python>=3.5
  - future
  - numpy>=1.12
  - scipy>=0.17
  - pandas>=0.23
  - xlsxwriter
  - xlrd
  - scikit-image>=0.13
  - h5py
  - silx
  - fabio
  - pyparsing
  - testfixtures
  - matplotlib
  - shapely
  - uncertainties
  - pint
  - jsonpickle
  - pyopencl
  - PyMca5
  - fisx
  - psutil
  - python-dateutil
  - SimpleITK

