#!/bin/bash
# . initcctbx

CCTBCBUILD=/usr/local/cctbx/build

export LIBTBX_BUILD=$CCTBCBUILD
export FONTCONFIG_PATH=$CCTBCBUILD/../base/etc/fonts

export LD_LIBRARY_PATH=$CCTBCBUILD/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CCTBCBUILD/bin:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CCTBCBUILD/../base/lib:$LD_LIBRARY_PATH

export PYTHONPATH=$PYTHONPATH:$CCTBCBUILD/lib:
export PYTHONPATH=$PYTHONPATH:$CCTBCBUILD/../modules
export PYTHONPATH=$PYTHONPATH:$CCTBCBUILD/../modules/cctbx_project
export PYTHONPATH=$PYTHONPATH:$CCTBCBUILD/../modules/cctbx_project/boost_adaptbx
export PYTHONPATH=$PYTHONPATH:$CCTBCBUILD/../modules/cctbx_project/libtbx/pythonpath

